# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/ui_code_tab_v3.ui',
# licensing of 'layouts/ui_code_tab_v3.ui' applies.
#
# Created: Wed Jan  9 22:00:24 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

"""
Created on Fri Nov 16 16:31:28 2018
@author: Praveen Noojipady
@email: noojipad@american.edu
@Project: pyNITA-GUI
License: MIT
Copyright (c)
"""
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 814)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 700))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 750))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setToolTipDuration(0)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setWordWrap(True)
        self.label_2.setMargin(1)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_5 = QtWidgets.QFrame(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777210, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Step1a_lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.Step1a_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step1a_lineEdit.setFont(font)
        self.Step1a_lineEdit.setMaxLength(32763)
        self.Step1a_lineEdit.setFrame(True)
        self.Step1a_lineEdit.setObjectName("Step1a_lineEdit")
        self.horizontalLayout_2.addWidget(self.Step1a_lineEdit)
        self.Step1a_toolButton = QtWidgets.QToolButton(self.frame_5)
        self.Step1a_toolButton.setObjectName("Step1a_toolButton")
        self.horizontalLayout_2.addWidget(self.Step1a_toolButton)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.Step1a_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.Step1a_pushButton.setEnabled(False)
        self.Step1a_pushButton.setObjectName("Step1a_pushButton")
        self.gridLayout_2.addWidget(self.Step1a_pushButton, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.Step1_label_2 = QtWidgets.QLabel(self.frame_5)
        self.Step1_label_2.setObjectName("Step1_label_2")
        self.gridLayout_9.addWidget(self.Step1_label_2, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_5, 1, 0, 1, 1)
        self.Step1_label_3 = QtWidgets.QLabel(self.tab1)
        self.Step1_label_3.setObjectName("Step1_label_3")
        self.gridLayout_19.addWidget(self.Step1_label_3, 0, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setToolTipDuration(14)
        self.frame_14.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_23.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.Step2_label_5 = QtWidgets.QLabel(self.frame_14)
        self.Step2_label_5.setObjectName("Step2_label_5")
        self.gridLayout_23.addWidget(self.Step2_label_5, 0, 0, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.Step1b_toolButton = QtWidgets.QToolButton(self.frame_14)
        self.Step1b_toolButton.setObjectName("Step1b_toolButton")
        self.gridLayout_29.addWidget(self.Step1b_toolButton, 0, 5, 1, 1)
        self.Step1b_lineEdit = QtWidgets.QLineEdit(self.frame_14)
        self.Step1b_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step1b_lineEdit.setFont(font)
        self.Step1b_lineEdit.setText("")
        self.Step1b_lineEdit.setObjectName("Step1b_lineEdit")
        self.gridLayout_29.addWidget(self.Step1b_lineEdit, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setObjectName("label_11")
        self.gridLayout_29.addWidget(self.label_11, 0, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem2, 0, 0, 1, 1)
        self.Step1b_pushButton = QtWidgets.QPushButton(self.frame_14)
        self.Step1b_pushButton.setEnabled(False)
        self.Step1b_pushButton.setObjectName("Step1b_pushButton")
        self.gridLayout_30.addWidget(self.Step1b_pushButton, 0, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_30, 2, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_14, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.tab1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_7.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setToolTipDuration(-1)
        self.label.setMidLineWidth(30)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.Step1c_buttonBox = QtWidgets.QDialogButtonBox(self.frame_9)
        self.Step1c_buttonBox.setEnabled(False)
        self.Step1c_buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Step1c_buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Step1c_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Step1c_buttonBox.setCenterButtons(False)
        self.Step1c_buttonBox.setObjectName("Step1c_buttonBox")
        self.horizontalLayout_4.addWidget(self.Step1c_buttonBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.Step1c_tableWidget = QtWidgets.QTableWidget(self.frame_9)
        self.Step1c_tableWidget.setEnabled(False)
        self.Step1c_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Step1c_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Step1c_tableWidget.setObjectName("Step1c_tableWidget")
        self.Step1c_tableWidget.setColumnCount(1)
        self.Step1c_tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step1c_tableWidget.setHorizontalHeaderItem(0, item)
        self.Step1c_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.Step1c_tableWidget, 3, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_9, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.frame_13 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setToolTipDuration(14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_25.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setObjectName("label_21")
        self.gridLayout_26.addWidget(self.label_21, 0, 1, 1, 1)
        self.Step2b_lineEdit = QtWidgets.QLineEdit(self.frame_13)
        self.Step2b_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step2b_lineEdit.setFont(font)
        self.Step2b_lineEdit.setText("")
        self.Step2b_lineEdit.setFrame(True)
        self.Step2b_lineEdit.setClearButtonEnabled(True)
        self.Step2b_lineEdit.setObjectName("Step2b_lineEdit")
        self.gridLayout_26.addWidget(self.Step2b_lineEdit, 0, 4, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_26, 1, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.DrawTraj_radioButton = QtWidgets.QRadioButton(self.frame_13)
        self.DrawTraj_radioButton.setEnabled(False)
        self.DrawTraj_radioButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DrawTraj_radioButton.setObjectName("DrawTraj_radioButton")
        self.gridLayout_27.addWidget(self.DrawTraj_radioButton, 0, 1, 1, 1)
        self.Step2b_pushButton = QtWidgets.QPushButton(self.frame_13)
        self.Step2b_pushButton.setEnabled(False)
        self.Step2b_pushButton.setObjectName("Step2b_pushButton")
        self.gridLayout_27.addWidget(self.Step2b_pushButton, 0, 2, 1, 1)
        self.Visualize_radioButton = QtWidgets.QRadioButton(self.frame_13)
        self.Visualize_radioButton.setEnabled(False)
        self.Visualize_radioButton.setObjectName("Visualize_radioButton")
        self.gridLayout_27.addWidget(self.Visualize_radioButton, 0, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_27, 2, 0, 1, 1)
        self.Step2_label_2 = QtWidgets.QLabel(self.frame_13)
        self.Step2_label_2.setObjectName("Step2_label_2")
        self.gridLayout_25.addWidget(self.Step2_label_2, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_13, 2, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.frame_15.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_26 = QtWidgets.QLabel(self.frame_15)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.Step2c_commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_15)
        self.Step2c_commandLinkButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step2c_commandLinkButton.sizePolicy().hasHeightForWidth())
        self.Step2c_commandLinkButton.setSizePolicy(sizePolicy)
        self.Step2c_commandLinkButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Step2c_commandLinkButton.setFont(font)
        self.Step2c_commandLinkButton.setToolTipDuration(-5)
        self.Step2c_commandLinkButton.setIconSize(QtCore.QSize(20, 20))
        self.Step2c_commandLinkButton.setAutoDefault(False)
        self.Step2c_commandLinkButton.setDescription("")
        self.Step2c_commandLinkButton.setObjectName("Step2c_commandLinkButton")
        self.horizontalLayout_5.addWidget(self.Step2c_commandLinkButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.Step2c_buttonBox = QtWidgets.QDialogButtonBox(self.frame_15)
        self.Step2c_buttonBox.setEnabled(False)
        self.Step2c_buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Step2c_buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Step2c_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Step2c_buttonBox.setCenterButtons(False)
        self.Step2c_buttonBox.setObjectName("Step2c_buttonBox")
        self.horizontalLayout_15.addWidget(self.Step2c_buttonBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.Step2c_tableWidget = QtWidgets.QTableWidget(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step2c_tableWidget.sizePolicy().hasHeightForWidth())
        self.Step2c_tableWidget.setSizePolicy(sizePolicy)
        self.Step2c_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Step2c_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Step2c_tableWidget.setLineWidth(17)
        self.Step2c_tableWidget.setObjectName("Step2c_tableWidget")
        self.Step2c_tableWidget.setColumnCount(1)
        self.Step2c_tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Step2c_tableWidget.setHorizontalHeaderItem(0, item)
        self.Step2c_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.Step2c_tableWidget, 1, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_15, 3, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_21.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.Step2a_lineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.Step2a_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step2a_lineEdit.setFont(font)
        self.Step2a_lineEdit.setMaxLength(32763)
        self.Step2a_lineEdit.setFrame(True)
        self.Step2a_lineEdit.setObjectName("Step2a_lineEdit")
        self.horizontalLayout_8.addWidget(self.Step2a_lineEdit)
        self.Step2a_toolButton = QtWidgets.QToolButton(self.frame_12)
        self.Step2a_toolButton.setObjectName("Step2a_toolButton")
        self.horizontalLayout_8.addWidget(self.Step2a_toolButton)
        self.gridLayout_21.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem5, 0, 0, 1, 1)
        self.Step2a_pushButton = QtWidgets.QPushButton(self.frame_12)
        self.Step2a_pushButton.setEnabled(False)
        self.Step2a_pushButton.setObjectName("Step2a_pushButton")
        self.gridLayout_24.addWidget(self.Step2a_pushButton, 0, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_24, 3, 0, 1, 1)
        self.Step1_label_5 = QtWidgets.QLabel(self.frame_12)
        self.Step1_label_5.setObjectName("Step1_label_5")
        self.gridLayout_21.addWidget(self.Step1_label_5, 1, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_12, 1, 0, 1, 1)
        self.Step1_label_6 = QtWidgets.QLabel(self.tab2)
        self.Step1_label_6.setObjectName("Step1_label_6")
        self.gridLayout_28.addWidget(self.Step1_label_6, 0, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMaximumSize(QtCore.QSize(16777202, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_18.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.Step2d_pushButton = QtWidgets.QPushButton(self.frame_16)
        self.Step2d_pushButton.setEnabled(False)
        self.Step2d_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777210))
        self.Step2d_pushButton.setAutoDefault(True)
        self.Step2d_pushButton.setDefault(False)
        self.Step2d_pushButton.setFlat(False)
        self.Step2d_pushButton.setObjectName("Step2d_pushButton")
        self.gridLayout_35.addWidget(self.Step2d_pushButton, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_16)
        self.label_25.setObjectName("label_25")
        self.gridLayout_35.addWidget(self.label_25, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem6, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_16, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_28.addItem(spacerItem7, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 3, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(16777210, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_10.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.Step3a_lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.Step3a_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step3a_lineEdit.setFont(font)
        self.Step3a_lineEdit.setMaxLength(32763)
        self.Step3a_lineEdit.setFrame(True)
        self.Step3a_lineEdit.setObjectName("Step3a_lineEdit")
        self.horizontalLayout_3.addWidget(self.Step3a_lineEdit)
        self.Step3a_toolButton = QtWidgets.QToolButton(self.frame_6)
        self.Step3a_toolButton.setObjectName("Step3a_toolButton")
        self.horizontalLayout_3.addWidget(self.Step3a_toolButton)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.Step1_label_4 = QtWidgets.QLabel(self.frame_6)
        self.Step1_label_4.setObjectName("Step1_label_4")
        self.gridLayout_10.addWidget(self.Step1_label_4, 1, 0, 1, 1)
        self.Step2_label_4 = QtWidgets.QLabel(self.frame_6)
        self.Step2_label_4.setObjectName("Step2_label_4")
        self.gridLayout_10.addWidget(self.Step2_label_4, 3, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.Step3b_toolButton = QtWidgets.QToolButton(self.frame_6)
        self.Step3b_toolButton.setObjectName("Step3b_toolButton")
        self.gridLayout_20.addWidget(self.Step3b_toolButton, 0, 5, 1, 1)
        self.Step3b_lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.Step3b_lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Step3b_lineEdit.setFont(font)
        self.Step3b_lineEdit.setText("")
        self.Step3b_lineEdit.setClearButtonEnabled(False)
        self.Step3b_lineEdit.setObjectName("Step3b_lineEdit")
        self.gridLayout_20.addWidget(self.Step3b_lineEdit, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_20.addWidget(self.label_10, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_20, 4, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem9, 0, 0, 1, 1)
        self.Step3ab_pushButton = QtWidgets.QPushButton(self.frame_6)
        self.Step3ab_pushButton.setEnabled(False)
        self.Step3ab_pushButton.setObjectName("Step3ab_pushButton")
        self.gridLayout_22.addWidget(self.Step3ab_pushButton, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_22, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.Step3c_pushButton = QtWidgets.QPushButton(self.frame_8)
        self.Step3c_pushButton.setEnabled(False)
        self.Step3c_pushButton.setObjectName("Step3c_pushButton")
        self.horizontalLayout.addWidget(self.Step3c_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Step3c_radioButton = QtWidgets.QRadioButton(self.frame_8)
        self.Step3c_radioButton.setEnabled(False)
        self.Step3c_radioButton.setObjectName("Step3c_radioButton")
        self.horizontalLayout_12.addWidget(self.Step3c_radioButton)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.Step3c_lineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.Step3c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.Step3c_lineEdit.sizePolicy().hasHeightForWidth())
        self.Step3c_lineEdit.setSizePolicy(sizePolicy)
        self.Step3c_lineEdit.setToolTipDuration(0)
        self.Step3c_lineEdit.setClearButtonEnabled(True)
        self.Step3c_lineEdit.setObjectName("Step3c_lineEdit")
        self.horizontalLayout_12.addWidget(self.Step3c_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_8, 2, 0, 1, 1)
        self.Step1_label_7 = QtWidgets.QLabel(self.tab3)
        self.Step1_label_7.setObjectName("Step1_label_7")
        self.gridLayout_6.addWidget(self.Step1_label_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab4)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.frame_10 = QtWidgets.QFrame(self.tab4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.save11 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save11.sizePolicy().hasHeightForWidth())
        self.save11.setSizePolicy(sizePolicy)
        self.save11.setText("")
        self.save11.setObjectName("save11")
        self.gridLayout_36.addWidget(self.save11, 0, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem11, 0, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem12, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_10)
        self.label_27.setObjectName("label_27")
        self.gridLayout_36.addWidget(self.label_27, 0, 0, 1, 1)
        self.plot11 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot11.sizePolicy().hasHeightForWidth())
        self.plot11.setSizePolicy(sizePolicy)
        self.plot11.setText("")
        self.plot11.setObjectName("plot11")
        self.gridLayout_36.addWidget(self.plot11, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_36, 14, 1, 1, 1)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.save16 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save16.sizePolicy().hasHeightForWidth())
        self.save16.setSizePolicy(sizePolicy)
        self.save16.setText("")
        self.save16.setObjectName("save16")
        self.gridLayout_41.addWidget(self.save16, 0, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem13, 0, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem14, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_10)
        self.label_32.setObjectName("label_32")
        self.gridLayout_41.addWidget(self.label_32, 0, 0, 1, 1)
        self.plot16 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot16.sizePolicy().hasHeightForWidth())
        self.plot16.setSizePolicy(sizePolicy)
        self.plot16.setText("")
        self.plot16.setObjectName("plot16")
        self.gridLayout_41.addWidget(self.plot16, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_41, 20, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 0, 3, 1, 1)
        self.plotAll = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotAll.sizePolicy().hasHeightForWidth())
        self.plotAll.setSizePolicy(sizePolicy)
        self.plotAll.setText("")
        self.plotAll.setChecked(False)
        self.plotAll.setObjectName("plotAll")
        self.gridLayout_3.addWidget(self.plotAll, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 0, 5, 1, 1)
        self.saveAll = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAll.sizePolicy().hasHeightForWidth())
        self.saveAll.setSizePolicy(sizePolicy)
        self.saveAll.setText("")
        self.saveAll.setObjectName("saveAll")
        self.gridLayout_3.addWidget(self.saveAll, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setAcceptDrops(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_10)
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_14.addWidget(self.label_35, 1, 1, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.save9 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save9.sizePolicy().hasHeightForWidth())
        self.save9.setSizePolicy(sizePolicy)
        self.save9.setText("")
        self.save9.setObjectName("save9")
        self.gridLayout_33.addWidget(self.save9, 0, 4, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem17, 0, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem18, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        self.label_22.setObjectName("label_22")
        self.gridLayout_33.addWidget(self.label_22, 0, 0, 1, 1)
        self.plot9 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot9.sizePolicy().hasHeightForWidth())
        self.plot9.setSizePolicy(sizePolicy)
        self.plot9.setText("")
        self.plot9.setObjectName("plot9")
        self.gridLayout_33.addWidget(self.plot9, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_33, 11, 1, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.save4 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save4.sizePolicy().hasHeightForWidth())
        self.save4.setSizePolicy(sizePolicy)
        self.save4.setText("")
        self.save4.setObjectName("save4")
        self.gridLayout_42.addWidget(self.save4, 0, 4, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_42.addItem(spacerItem19, 0, 5, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_42.addItem(spacerItem20, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setObjectName("label_12")
        self.gridLayout_42.addWidget(self.label_12, 0, 0, 1, 1)
        self.plot4 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot4.sizePolicy().hasHeightForWidth())
        self.plot4.setSizePolicy(sizePolicy)
        self.plot4.setText("")
        self.plot4.setObjectName("plot4")
        self.gridLayout_42.addWidget(self.plot4, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_42, 6, 1, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.save8 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save8.sizePolicy().hasHeightForWidth())
        self.save8.setSizePolicy(sizePolicy)
        self.save8.setText("")
        self.save8.setObjectName("save8")
        self.gridLayout_31.addWidget(self.save8, 0, 4, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem21, 0, 5, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem22, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_10)
        self.label_20.setObjectName("label_20")
        self.gridLayout_31.addWidget(self.label_20, 0, 0, 1, 1)
        self.plot8 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot8.sizePolicy().hasHeightForWidth())
        self.plot8.setSizePolicy(sizePolicy)
        self.plot8.setText("")
        self.plot8.setObjectName("plot8")
        self.gridLayout_31.addWidget(self.plot8, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_31, 10, 1, 1, 1)
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.save12 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save12.sizePolicy().hasHeightForWidth())
        self.save12.setSizePolicy(sizePolicy)
        self.save12.setText("")
        self.save12.setObjectName("save12")
        self.gridLayout_37.addWidget(self.save12, 0, 4, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem23, 0, 5, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem24, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_10)
        self.label_28.setObjectName("label_28")
        self.gridLayout_37.addWidget(self.label_28, 0, 0, 1, 1)
        self.plot12 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot12.sizePolicy().hasHeightForWidth())
        self.plot12.setSizePolicy(sizePolicy)
        self.plot12.setText("")
        self.plot12.setObjectName("plot12")
        self.gridLayout_37.addWidget(self.plot12, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_37, 16, 1, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem25 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem25, 0, 3, 1, 1)
        self.save7 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save7.sizePolicy().hasHeightForWidth())
        self.save7.setSizePolicy(sizePolicy)
        self.save7.setText("")
        self.save7.setObjectName("save7")
        self.gridLayout_17.addWidget(self.save7, 0, 4, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem26, 0, 5, 1, 1)
        self.plot7 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot7.sizePolicy().hasHeightForWidth())
        self.plot7.setSizePolicy(sizePolicy)
        self.plot7.setText("")
        self.plot7.setObjectName("plot7")
        self.gridLayout_17.addWidget(self.plot7, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_17, 9, 1, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.save2 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save2.sizePolicy().hasHeightForWidth())
        self.save2.setSizePolicy(sizePolicy)
        self.save2.setText("")
        self.save2.setObjectName("save2")
        self.gridLayout_12.addWidget(self.save2, 0, 4, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem27, 0, 5, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem28, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 0, 0, 1, 1)
        self.plot2 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot2.sizePolicy().hasHeightForWidth())
        self.plot2.setSizePolicy(sizePolicy)
        self.plot2.setText("")
        self.plot2.setObjectName("plot2")
        self.gridLayout_12.addWidget(self.plot2, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 4, 1, 1, 1)
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        spacerItem29 = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_43.addItem(spacerItem29, 0, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_10)
        self.label_34.setObjectName("label_34")
        self.gridLayout_43.addWidget(self.label_34, 0, 1, 1, 1)
        self.Step4_DateValue = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_DateValue.sizePolicy().hasHeightForWidth())
        self.Step4_DateValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step4_DateValue.setFont(font)
        self.Step4_DateValue.setToolTipDuration(-1)
        self.Step4_DateValue.setFrame(True)
        self.Step4_DateValue.setObjectName("Step4_DateValue")
        self.gridLayout_43.addWidget(self.Step4_DateValue, 0, 2, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_43.addItem(spacerItem30, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_43, 15, 1, 1, 1)
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.save14 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save14.sizePolicy().hasHeightForWidth())
        self.save14.setSizePolicy(sizePolicy)
        self.save14.setText("")
        self.save14.setObjectName("save14")
        self.gridLayout_39.addWidget(self.save14, 0, 4, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_39.addItem(spacerItem31, 0, 5, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_39.addItem(spacerItem32, 0, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_10)
        self.label_30.setObjectName("label_30")
        self.gridLayout_39.addWidget(self.label_30, 0, 0, 1, 1)
        self.plot14 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot14.sizePolicy().hasHeightForWidth())
        self.plot14.setSizePolicy(sizePolicy)
        self.plot14.setText("")
        self.plot14.setObjectName("plot14")
        self.gridLayout_39.addWidget(self.plot14, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_39, 18, 1, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem33, 0, 5, 1, 1)
        self.save3 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save3.sizePolicy().hasHeightForWidth())
        self.save3.setSizePolicy(sizePolicy)
        self.save3.setText("")
        self.save3.setObjectName("save3")
        self.gridLayout_13.addWidget(self.save3, 0, 4, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem34, 0, 3, 1, 1)
        self.plot3 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot3.sizePolicy().hasHeightForWidth())
        self.plot3.setSizePolicy(sizePolicy)
        self.plot3.setText("")
        self.plot3.setObjectName("plot3")
        self.gridLayout_13.addWidget(self.plot3, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 5, 1, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.save5 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save5.sizePolicy().hasHeightForWidth())
        self.save5.setSizePolicy(sizePolicy)
        self.save5.setText("")
        self.save5.setObjectName("save5")
        self.gridLayout_15.addWidget(self.save5, 0, 4, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem35, 0, 5, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem36, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 0, 0, 1, 1)
        self.plot5 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot5.sizePolicy().hasHeightForWidth())
        self.plot5.setSizePolicy(sizePolicy)
        self.plot5.setText("")
        self.plot5.setObjectName("plot5")
        self.gridLayout_15.addWidget(self.plot5, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 7, 1, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.save6 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save6.sizePolicy().hasHeightForWidth())
        self.save6.setSizePolicy(sizePolicy)
        self.save6.setText("")
        self.save6.setObjectName("save6")
        self.gridLayout_16.addWidget(self.save6, 0, 4, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem37, 0, 5, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem38, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setObjectName("label_14")
        self.gridLayout_16.addWidget(self.label_14, 0, 0, 1, 1)
        self.plot6 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot6.sizePolicy().hasHeightForWidth())
        self.plot6.setSizePolicy(sizePolicy)
        self.plot6.setText("")
        self.plot6.setObjectName("plot6")
        self.gridLayout_16.addWidget(self.plot6, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 8, 1, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.save13 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save13.sizePolicy().hasHeightForWidth())
        self.save13.setSizePolicy(sizePolicy)
        self.save13.setText("")
        self.save13.setObjectName("save13")
        self.gridLayout_38.addWidget(self.save13, 0, 4, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem39, 0, 5, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem40, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_10)
        self.label_29.setObjectName("label_29")
        self.gridLayout_38.addWidget(self.label_29, 0, 0, 1, 1)
        self.plot13 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot13.sizePolicy().hasHeightForWidth())
        self.plot13.setSizePolicy(sizePolicy)
        self.plot13.setText("")
        self.plot13.setObjectName("plot13")
        self.gridLayout_38.addWidget(self.plot13, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_38, 17, 1, 1, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.save15 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save15.sizePolicy().hasHeightForWidth())
        self.save15.setSizePolicy(sizePolicy)
        self.save15.setText("")
        self.save15.setObjectName("save15")
        self.gridLayout_40.addWidget(self.save15, 0, 4, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem41, 0, 5, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem42, 0, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_10)
        self.label_31.setObjectName("label_31")
        self.gridLayout_40.addWidget(self.label_31, 0, 0, 1, 1)
        self.plot15 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot15.sizePolicy().hasHeightForWidth())
        self.plot15.setSizePolicy(sizePolicy)
        self.plot15.setText("")
        self.plot15.setObjectName("plot15")
        self.gridLayout_40.addWidget(self.plot15, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_40, 19, 1, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.save10 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save10.sizePolicy().hasHeightForWidth())
        self.save10.setSizePolicy(sizePolicy)
        self.save10.setText("")
        self.save10.setObjectName("save10")
        self.gridLayout_34.addWidget(self.save10, 0, 4, 1, 1)
        self.plot10 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot10.sizePolicy().hasHeightForWidth())
        self.plot10.setSizePolicy(sizePolicy)
        self.plot10.setText("")
        self.plot10.setObjectName("plot10")
        self.gridLayout_34.addWidget(self.plot10, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        self.label_24.setObjectName("label_24")
        self.gridLayout_34.addWidget(self.label_24, 0, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem43, 0, 3, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem44, 0, 5, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_34, 12, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem45 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem45, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_10)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 0, 3, 1, 1)
        self.Step4_ValueChange_Date1 = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_ValueChange_Date1.sizePolicy().hasHeightForWidth())
        self.Step4_ValueChange_Date1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step4_ValueChange_Date1.setFont(font)
        self.Step4_ValueChange_Date1.setFrame(True)
        self.Step4_ValueChange_Date1.setObjectName("Step4_ValueChange_Date1")
        self.gridLayout_11.addWidget(self.Step4_ValueChange_Date1, 0, 2, 1, 1)
        self.Step4_ValueChange_Date2 = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_ValueChange_Date2.sizePolicy().hasHeightForWidth())
        self.Step4_ValueChange_Date2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step4_ValueChange_Date2.setFont(font)
        self.Step4_ValueChange_Date2.setReadOnly(False)
        self.Step4_ValueChange_Date2.setObjectName("Step4_ValueChange_Date2")
        self.gridLayout_11.addWidget(self.Step4_ValueChange_Date2, 0, 4, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 13, 1, 1, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_38 = QtWidgets.QLabel(self.frame_10)
        self.label_38.setToolTipDuration(-4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_45.addWidget(self.label_38, 0, 5, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_45.addItem(spacerItem46, 0, 6, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(184, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_45.addItem(spacerItem47, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_10)
        self.label_37.setObjectName("label_37")
        self.gridLayout_45.addWidget(self.label_37, 0, 1, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_45.addItem(spacerItem48, 0, 4, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_45, 2, 1, 1, 1)
        self.gridLayout_32.addWidget(self.frame_10, 1, 0, 1, 1)
        self.Step1_label_8 = QtWidgets.QLabel(self.tab4)
        self.Step1_label_8.setObjectName("Step1_label_8")
        self.gridLayout_32.addWidget(self.Step1_label_8, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem49)
        self.Step4_pushButton = QtWidgets.QPushButton(self.tab4)
        self.Step4_pushButton.setEnabled(False)
        self.Step4_pushButton.setObjectName("Step4_pushButton")
        self.horizontalLayout_6.addWidget(self.Step4_pushButton)
        self.gridLayout_32.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem50, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab4, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; text-decoration: underline; color:#0f80ff;\">pyNITA</span></p><p><span style=\" font-size:18pt;\">Welcome to pyNITA user interface(UI), a python implementation of Noise Insensitive Trajectory Algorithm (NITA). The pyNITA UI enables a step-by-step approach to parameterize NITA input parameters, hand draw phenological trajectories, optimize input parameters, and compute image stack metrics for time-series satellite remote sensing data. </span></p><p><span style=\" font-size:14pt; font-weight:600;\">Reference: </span><span style=\" font-size:14pt;\">Scientific Reports </span><a href=\"https://www.nature.com/articles/srep35129\"><span style=\" font-size:14pt; text-decoration: underline; color:#0000ff;\">Article</span></a></p><p><span style=\" font-size:14pt; font-weight:600;\">Source Code:</span><span style=\" font-size:14pt;\"> Available from GitHub, </span><a href=\"https://github.com/fengly20/pynita/\"><span style=\" text-decoration: underline; color:#0000ff;\">Click here</span></a></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "pyNITA", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Browse:", None, -1))
        self.Step1a_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Working Directory", None, -1))
        self.Step1a_toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.Step1a_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.Step1_label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step1a: Select Working Directory</span></p></body></html>", None, -1))
        self.Step1_label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0f80ff;\">Step1: Configure NITA Parameters</span></p></body></html>", None, -1))
        self.Step2_label_5.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step1b: Select User Configuration File</span></p></body></html>", None, -1))
        self.Step1b_toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.Step1b_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "User Configuration File(.ini)", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Browse:", None, -1))
        self.Step1b_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step1c: Specify Control Parameters</span></p></body></html>", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Save Changes:", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "ProjectName", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "user_vi", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "value_limits", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "doy_limits", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "date_limits", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "bail_thresh", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "noise_thresh", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "penalty", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "filter_dist", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "pct", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(10).setText(QtWidgets.QApplication.translate("MainWindow", "max_complex", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(11).setText(QtWidgets.QApplication.translate("MainWindow", "min_complex", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(12).setText(QtWidgets.QApplication.translate("MainWindow", "filter_opt", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(13).setText(QtWidgets.QApplication.translate("MainWindow", "vi_change_thresh", None, -1))
        self.Step1c_tableWidget.verticalHeaderItem(14).setText(QtWidgets.QApplication.translate("MainWindow", "time_step", None, -1))
        self.Step1c_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Parameters", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtWidgets.QApplication.translate("MainWindow", "Step1", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Enter OBJECTIDs:", None, -1))
        self.Step2b_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "e.g.,1,2,3,...n or 9999(all)", None, -1))
        self.DrawTraj_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Draw Trajectories", None, -1))
        self.Step2b_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.Visualize_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Visualize", None, -1))
        self.Step2_label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step2b: Plot NITA Points</span></p></body></html>", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Note: Parameter set are saved to the user configuration file</span></p></body></html>", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step2c: Specify NITA Parameter Set</span></p></body></html>", None, -1))
        self.Step2c_commandLinkButton.setText(QtWidgets.QApplication.translate("MainWindow", "Load Default Set", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Save Changes:", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "bail_thresh_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "noise_thresh_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "penalty_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "filter_dist_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "pct_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "max_complex_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "min_complex_set", None, -1))
        self.Step2c_tableWidget.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "filter_opt_set", None, -1))
        self.Step2c_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Parameter Set", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Browse:", None, -1))
        self.Step2a_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Points Extraction File (.csv)", None, -1))
        self.Step2a_toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.Step2a_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.Step1_label_5.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step2a: Select Points Extraction File</span></p></body></html>", None, -1))
        self.Step1_label_6.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0f80ff;\">Step2: NITA Parameter Optimization</span></p></body></html>", None, -1))
        self.Step2d_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 2d: Run Optimization</span></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtWidgets.QApplication.translate("MainWindow", "Step2", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Browse:", None, -1))
        self.Step3a_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Image Stack File (.tif)", None, -1))
        self.Step3a_toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.Step1_label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step3a: Select Image </span><span style=\" font-weight:600; color:#ff0000;\">Stack</span><span style=\" font-weight:600; color:#ff0000;\"> File</span><span style=\" font-weight:600;\"> (</span><span style=\" font-weight:600; font-style:italic;\">*.tif</span><span style=\" font-weight:600;\">)</span></p></body></html>", None, -1))
        self.Step2_label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step3b: Select Image </span><span style=\" font-weight:600; color:#8000ff;\">Dates File</span><span style=\" font-weight:600;\">(</span><span style=\" font-weight:600; font-style:italic;\">.csv</span><span style=\" font-weight:600;\">)</span></p></body></html>", None, -1))
        self.Step3b_toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.Step3b_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Image Dates File (.csv)", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Browse:", None, -1))
        self.Step3ab_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.Step3c_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.Step3c_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Parallelization", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Workers:", None, -1))
        self.Step3c_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "e.g., 2,3,4,...n cores", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 3c: Generate Image Metrics</span></p></body></html>", None, -1))
        self.Step1_label_7.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0f80ff;\">Step3: Compute Image Stack Metrics</span></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), QtWidgets.QApplication.translate("MainWindow", "Step3", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "11. Date Value", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "16. Bailcut", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "1. All", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Plot and Save Options:", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "9. Value Change All", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "4. Dist Duration", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "8. Post-Dist Magnitude", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "12. Recovery", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "7. Post-Dist Slope", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "2. Complexity", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Date:</span></p></body></html>", None, -1))
        self.Step4_DateValue.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "2002000", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "14. Linear Error", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "3. Dist Date", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "5. Dist Magnitude", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "6. Dist Slope", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "13. Recovery CMP", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "15. Noise", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "10. Value Change Custom", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Start Date:</span></p></body></html>", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">End Date:</span></p></body></html>", None, -1))
        self.Step4_ValueChange_Date1.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "2002000", None, -1))
        self.Step4_ValueChange_Date2.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "2016900", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Save</span></p></body></html>", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Plot</span></p></body></html>", None, -1))
        self.Step1_label_8.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0f80ff;\">Step4: Image Stack Metric Outputs</span></p></body></html>", None, -1))
        self.Step4_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), QtWidgets.QApplication.translate("MainWindow", "Step4", None, -1))

